# Generated by Django 4.0.2 on 2022-05-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubropresupuestal', '0003_rubropresupuestal_idpadre'),
        ('solicitudpresupuestalcabecera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudpresupuestaldetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('rubropresupuestalid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rubropresupuestal.rubropresupuestal')),
                ('solicitudpresupuestalcabeceraid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='solicitudpresupuestalcabecera.solicitudpresupuestalcabecera')),
            ],
        ),
    ]
