# Generated by Django 4.0.2 on 2022-05-07 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudpresupuestalcabecera', '0001_initial'),
        ('solicitudpresupuestaldetalle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpresupuestaldetalle',
            name='solicitudpresupuestalcabeceraid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudpresupuestaldetalle', to='solicitudpresupuestalcabecera.solicitudpresupuestalcabecera'),
        ),
    ]
