# Generated by Django 4.0.2 on 2022-09-14 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuenterecurso', '0001_initial'),
        ('solicitudpresupuestaldetalle', '0002_alter_solicitudpresupuestaldetalle_solicitudpresupuestalcabeceraid'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpresupuestaldetalle',
            name='fuenterecursoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='fuenterecurso.fuenterecurso'),
        ),
        migrations.AddConstraint(
            model_name='solicitudpresupuestaldetalle',
            constraint=models.UniqueConstraint(fields=('solicitudpresupuestalcabeceraid', 'fuenterecursoid', 'rubropresupuestalid'), name='UK_solicitudpresupuestalcabeceraid_fuenterecursoid_rubropresupuestalid_unique'),
        ),
    ]
