# Generated by Django 4.0.2 on 2022-02-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('institucioneducativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='usuarioid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.usuario'),
        ),
    ]
