# Generated by Django 4.0.2 on 2022-03-01 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('institucioneducativa', '0002_alter_institucioneducativa_usuarioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='usuarioid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.usuario', unique=True),
        ),
    ]
