# Generated by Django 4.0.2 on 2022-11-11 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institucioneducativa', '0003_alter_institucioneducativa_usuarioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='usuarioid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
