# Generated by Django 4.0.2 on 2022-11-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, default='Institucion', max_length=255, null=True, verbose_name='Rol del Usuario'),
        ),
    ]
