# Generated by Django 4.0.2 on 2022-03-21 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyeccionpresupuestalcabecera', '0001_initial'),
        ('rubropresupuestal', '0003_rubropresupuestal_idpadre'),
        ('fuenterecurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyeccionpresupuestaldetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fuenterecuroid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fuenterecurso.fuenterecurso')),
                ('proyeccionpresupuestalid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyeccionpresupuestalcabecera.proyeccionpresupuestalcabecera')),
                ('rubropresupuestalid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rubropresupuestal.rubropresupuestal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='proyeccionpresupuestaldetalle',
            constraint=models.UniqueConstraint(fields=('proyeccionpresupuestalid', 'fuenterecuroid', 'rubropresupuestalid'), name='UK_proyeccionpresupuestalid_fuenterecuroid_rubropresupuestalid_unique'),
        ),
    ]
