# Generated by Django 4.0.2 on 2022-03-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyeccionpresupuestalcabecera', '0001_initial'),
        ('proyeccionpresupuestaldetalle', '0002_remove_proyeccionpresupuestaldetalle_uk_proyeccionpresupuestalid_fuenterecuroid_rubropresupuestalid_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccionpresupuestaldetalle',
            name='proyeccionpresupuestalid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proyeccionpresupuestaldetalle', to='proyeccionpresupuestalcabecera.proyeccionpresupuestalcabecera'),
        ),
    ]
