# Generated by Django 4.0.2 on 2022-04-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucioneducativa', '0003_alter_institucioneducativa_usuarioid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodocumento', models.IntegerField()),
                ('consecutivo', models.PositiveIntegerField()),
                ('institucioneducativaid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institucioneducativa.institucioneducativa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='consecutivo',
            constraint=models.UniqueConstraint(fields=('tipodocumento', 'institucioneducativaid', 'consecutivo'), name='UK_tipodocumento_institucioneducativaid_unique'),
        ),
    ]
