# Generated by Django 4.0.2 on 2022-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0002_remove_tercero_uk_tercero_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tercero',
            name='UK_tercero_unique',
        ),
        migrations.AlterField(
            model_name='tercero',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
