# Generated by Django 4.0.2 on 2022-03-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubropresupuestal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubropresupuestal',
            name='rubropresupuestalidpadre',
        ),
    ]
