# Generated by Django 4.0.2 on 2022-03-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubropresupuestal', '0002_remove_rubropresupuestal_rubropresupuestalidpadre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubropresupuestal',
            name='idpadre',
            field=models.BigIntegerField(null=True),
        ),
    ]
