# Generated by Django 4.0.2 on 2022-08-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresopresupuestal', '0004_alter_ingresopresupuestal_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresopresupuestal',
            name='estado',
            field=models.CharField(default='Procesado', max_length=50),
        ),
        migrations.AddField(
            model_name='ingresopresupuestal',
            name='objeto',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
