# Generated by Django 4.0.2 on 2022-09-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagopresupuestal', '0002_pagopresupuestal_estado_pagopresupuestal_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagopresupuestal',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
