# Generated by Django 4.0.2 on 2022-07-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubropresupuestal', '0003_rubropresupuestal_idpadre'),
        ('fuenterecurso', '0001_initial'),
        ('modificacionproyeccionpresupuestalcabecera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modificacionproyeccionpresupuestaldetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fuenterecursoid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fuenterecurso.fuenterecurso')),
                ('modificacionproyeccionpresupuestalid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modificacionproyeccionpresupuestaldetalle', to='modificacionproyeccionpresupuestalcabecera.modificacionproyeccionpresupuestalcabecera')),
                ('rubropresupuestalid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rubropresupuestal.rubropresupuestal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='modificacionproyeccionpresupuestaldetalle',
            constraint=models.UniqueConstraint(fields=('modificacionproyeccionpresupuestalid', 'fuenterecursoid', 'rubropresupuestalid'), name='UK_modificacionproyeccionpresupuestalid_fuenterecursoid_rubropresupuestalid_unique'),
        ),
    ]
