# Generated by Django 4.0.2 on 2022-09-17 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipocontrato', '0001_initial'),
        ('registropresupuestal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropresupuestal',
            name='contratonumero',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registropresupuestal',
            name='estado',
            field=models.CharField(default='Procesado', max_length=50),
        ),
        migrations.AddField(
            model_name='registropresupuestal',
            name='fechafincontrato',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='registropresupuestal',
            name='fechainiciocontrato',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='registropresupuestal',
            name='objeto',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='registropresupuestal',
            name='tipocontratoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tipocontrato.tipocontrato'),
        ),
    ]
