# Generated by Django 4.0.2 on 2022-09-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registropresupuestal', '0002_registropresupuestal_contratonumero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropresupuestal',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
