# Generated by Django 4.0.2 on 2022-05-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucioneducativa', '0003_alter_institucioneducativa_usuarioid'),
        ('rubropresupuestal', '0003_rubropresupuestal_idpadre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificadodisponibilidadpresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('diasvalidez', models.DecimalField(decimal_places=6, max_digits=18)),
                ('observacion', models.CharField(max_length=500)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('institucioneducativaid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institucioneducativa.institucioneducativa')),
                ('rubropresupuestalid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rubropresupuestal.rubropresupuestal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='certificadodisponibilidadpresupuestal',
            constraint=models.UniqueConstraint(fields=('institucioneducativaid', 'consecutivo'), name='UK_CDP_institucioneducativaid_consecutivo_unique'),
        ),
    ]
