# Generated by Django 4.0.2 on 2022-09-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificadodisponibilidadpresupuestal', '0002_remove_certificadodisponibilidadpresupuestal_rubropresupuestalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadodisponibilidadpresupuestal',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
