# Generated by Django 4.0.2 on 2022-03-18 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucioneducativa', '0003_alter_institucioneducativa_usuarioid'),
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyeccionpresupuestalcabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=5000)),
                ('institucioneducativaid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institucioneducativa.institucioneducativa')),
                ('periodoid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='periodo.periodo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='proyeccionpresupuestalcabecera',
            constraint=models.UniqueConstraint(fields=('periodoid', 'institucioneducativaid'), name='UK_periodo_institucioneducativa_unique'),
        ),
    ]
