# Generated by Django 4.0.2 on 2022-05-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucioneducativa', '0003_alter_institucioneducativa_usuarioid'),
        ('personalplanta', '0001_initial'),
        ('tercero', '0002_remove_tercero_uk_tercero_unique_and_more'),
        ('tipocontrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudpresupuestalcabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=5000)),
                ('fechainiciocontrato', models.DateField()),
                ('fechafincontrato', models.DateField()),
                ('contratonumero', models.CharField(max_length=50)),
                ('institucioneducativaid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institucioneducativa.institucioneducativa')),
                ('personalplantaidsolicitado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='FK_personalplantaidsolicitado', to='personalplanta.personalplanta')),
                ('personalplantaidsolicitante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='FK_personalplantaidsolicitante', to='personalplanta.personalplanta')),
                ('terceroid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tercero.tercero')),
                ('tipocontratoid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tipocontrato.tipocontrato')),
            ],
        ),
        migrations.AddConstraint(
            model_name='solicitudpresupuestalcabecera',
            constraint=models.UniqueConstraint(fields=('institucioneducativaid', 'consecutivo'), name='UK_solicitudpresupuestalcabecera_institucioneducativaid_consecutivo_unique'),
        ),
    ]
