# Generated by Django 4.0.2 on 2022-09-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudpresupuestalcabecera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpresupuestalcabecera',
            name='estado',
            field=models.CharField(default='Procesado', max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudpresupuestalcabecera',
            name='objeto',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
