# Generated by Django 4.0.2 on 2022-09-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudpresupuestalcabecera', '0003_remove_solicitudpresupuestalcabecera_contratonumero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpresupuestalcabecera',
            name='observacion',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
