# Generated by Django 4.0.2 on 2022-09-23 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucioneducativa', '0003_alter_institucioneducativa_usuarioid'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoriainstitucioneducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucioneducativaid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='institucioneducativa.institucioneducativa')),
                ('usuarioid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.usuario')),
            ],
        ),
    ]
