# Generated by Django 4.0.2 on 2022-09-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorinstitucioneducativa', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='auditoriainstitucioneducativa',
            constraint=models.UniqueConstraint(fields=('institucioneducativaid', 'usuarioid'), name='UK_institucioneducativaid_usuarioid_unique'),
        ),
    ]
