# Generated by Django 4.0.2 on 2022-11-11 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditorinstitucioneducativa', '0002_auditoriainstitucioneducativa_uk_institucioneducativaid_usuarioid_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriainstitucioneducativa',
            name='usuarioid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
