# Generated by Django 4.0.2 on 2022-09-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntos',
            name='archivobase64',
            field=models.FileField(upload_to='files/'),
        ),
    ]
