# Generated by Django 4.0.2 on 2022-09-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0002_alter_adjuntos_archivobase64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjuntos',
            old_name='consecutivo',
            new_name='documnetoid',
        ),
        migrations.RenameField(
            model_name='adjuntos',
            old_name='tipodocumento',
            new_name='tipo',
        ),
    ]
