# Generated by Django 4.0.2 on 2022-08-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaudopresupuestal', '0003_recaudopresupuestal_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudopresupuestal',
            name='observacion',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
